langauge: ruby
bundler_args: --without development
script: "SPEC_OPTS='--format=d' rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
